apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-frontend
  labels:
    service: todoapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp-frontend
  template:
    metadata:
      labels:
        app: todoapp-frontend
    spec:
      containers:
      - name: todoapp-frontend
        image: trinhnt30/todoapp-frontend:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
      restartPolicy: Always