apiVersion: v1
kind: Service
metadata:
  labels:
    service: todoapp-frontend
  name: todoapp-frontend
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 80
  selector:
    app: todoapp-frontend